export const invoices = [
  {
    id: "MS7421498",
    amount: 2100,
    timePeriod: new Date(),
    creditsUsed: 540,
    creditsLimit: 1000,
    isPaid: false,
    receiptUrl: "https://google.com",
  },
  {
    id: "MS7421499",
    amount: 2100,
    timePeriod: new Date(),
    creditsUsed: 540,
    creditsLimit: 1000,
    isPaid: false,
    receiptUrl: "https://google.com",
  },
  {
    id: "MS7421500",
    amount: 700,
    timePeriod: new Date(),
    creditsUsed: 891,
    creditsLimit: 1000,
    isPaid: true,
    receiptUrl: "https://google.com",
  },
  {
    id: "MS7421501",
    amount: 2100,
    timePeriod: new Date(),
    creditsUsed: 300,
    creditsLimit: 1000,
    isPaid: true,
    receiptUrl: "https://google.com",
  },
  {
    id: "MS7421502",
    amount: 2100,
    timePeriod: new Date(),
    creditsUsed: 555,
    creditsLimit: 1000,
    isPaid: true,
    receiptUrl: "https://google.com",
  },
  {
    id: "MS7421503",
    amount: 2100,
    timePeriod: new Date(),
    creditsUsed: 891,
    creditsLimit: 1000,
    isPaid: false,
    receiptUrl: "https://google.com",
  },
  {
    id: "MS7421504",
    amount: 700,
    timePeriod: new Date(),
    creditsUsed: 434,
    creditsLimit: 1000,
    isPaid: true,
    receiptUrl: "https://google.com",
  },
  {
    id: "MS7421505",
    amount: 3000,
    timePeriod: new Date(),
    creditsUsed: 213,
    creditsLimit: 1000,
    isPaid: true,
    receiptUrl: "https://google.com",
  },
  {
    id: "MS7421506",
    amount: 1200,
    timePeriod: new Date(),
    creditsUsed: 322,
    creditsLimit: 1000,
    isPaid: true,
    receiptUrl: "https://google.com",
  },
  {
    id: "MS7421507",
    amount: 1900,
    timePeriod: new Date(),
    creditsUsed: 632,
    creditsLimit: 1000,
    isPaid: false,
    receiptUrl: "https://google.com",
  },
  {
    id: "MS7421508",
    amount: 2100,
    timePeriod: new Date(),
    creditsUsed: 540,
    creditsLimit: 1000,
    isPaid: false,
    receiptUrl: "https://google.com",
  },
  {
    id: "MS7421509",
    amount: 2100,
    timePeriod: new Date(),
    creditsUsed: 540,
    creditsLimit: 1000,
    isPaid: false,
    receiptUrl: "https://google.com",
  },
  {
    id: "MS7421510",
    amount: 700,
    timePeriod: new Date(),
    creditsUsed: 891,
    creditsLimit: 1000,
    isPaid: true,
    receiptUrl: "https://google.com",
  },
  {
    id: "MS7421511",
    amount: 2100,
    timePeriod: new Date(),
    creditsUsed: 300,
    creditsLimit: 1000,
    isPaid: true,
    receiptUrl: "https://google.com",
  },
];
